# Generated by Django 6.0.3 on 2026-03-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_is_superuser_and_more'),
        ('users', '0002_user_qr_code_fields'),
    ]

    operations = [
    ]
